"""Build config/universe.txt from live index constituents.

Blend (per the design spec): S&P 500 + Nasdaq-100 + S&P 400 mid-caps,
deduped, with tickers normalized to yfinance format (e.g. BRK.B -> BRK-B).

Run:  python tools/build_universe.py
Requires: requests, pandas, lxml (lxml is a tooling-only dependency; the
weekly pipeline itself does not need it).
"""
import re
import sys
from datetime import date
from io import StringIO
from pathlib import Path

import pandas as pd
import requests

HEADERS = {"User-Agent": "Mozilla/5.0 (market_insights universe-builder)"}
SYMBOL_COLS = ("Symbol", "Ticker", "Ticker symbol")
SOURCES = [
    ("S&P 500", "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"),
    ("Nasdaq-100", "https://en.wikipedia.org/wiki/Nasdaq-100"),
    ("S&P 400 (mid-cap)", "https://en.wikipedia.org/wiki/List_of_S%26P_400_companies"),
]
VALID = re.compile(r"^[A-Z][A-Z0-9-]*$")


def _normalize(sym) -> str | None:
    if not isinstance(sym, str):
        return None
    s = sym.strip().upper().replace(".", "-")
    return s if VALID.match(s) else None


def _symbols_from(url: str) -> list:
    resp = requests.get(url, headers=HEADERS, timeout=30)
    resp.raise_for_status()
    tables = pd.read_html(StringIO(resp.text))
    for table in tables:
        for col in SYMBOL_COLS:
            if col in table.columns:
                out = []
                for raw in table[col].tolist():
                    s = _normalize(raw)
                    if s:
                        out.append(s)
                if out:
                    return out
    raise RuntimeError(f"no symbol column found at {url}")


def build() -> list:
    seen, universe, provenance = set(), [], []
    for name, url in SOURCES:
        try:
            syms = _symbols_from(url)
        except Exception as e:  # one bad source shouldn't sink the build
            print(f"WARNING: {name} fetch failed: {e}", file=sys.stderr)
            provenance.append(f"{name}: FAILED ({e})")
            continue
        added = 0
        for s in syms:
            if s not in seen:
                seen.add(s)
                universe.append(s)
                added += 1
        provenance.append(f"{name}: {len(syms)} listed, {added} new")
        print(f"{name}: {len(syms)} listed, {added} new")
    return universe, provenance


def main():
    universe, provenance = build()
    if not universe:
        print("ERROR: no symbols collected; leaving universe.txt unchanged", file=sys.stderr)
        sys.exit(1)
    out_path = Path(__file__).resolve().parent.parent / "config" / "universe.txt"
    header = [
        "# Ticker universe — one symbol per line. Lines starting with '#' are comments.",
        f"# Generated by tools/build_universe.py on {date.today().isoformat()}",
        "# Blend: S&P 500 + Nasdaq-100 + S&P 400 mid-caps (yfinance-normalized).",
    ] + [f"#   {p}" for p in provenance] + [f"# Total unique: {len(universe)}", ""]
    out_path.write_text("\n".join(header + universe) + "\n")
    print(f"wrote {out_path}: {len(universe)} unique tickers")


if __name__ == "__main__":
    main()
